# Generated by Django 4.2.9 on 2024-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Дано вещественное число A. Вычислить x = a**4, при a < 10; x = a при a > 61, в противном случае x  = a − sin(a**2)).', max_length=255, verbose_name='Формулировка задачи')),
                ('a', models.FloatField(default=0, verbose_name='Значение А')),
                ('result', models.FloatField(default=0, verbose_name='Результат')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'Таблица задачи',
                'verbose_name_plural': 'Таблицы задачи',
                'ordering': ('-id', '-a'),
            },
        ),
    ]
