# Generated by Django 4.2.9 on 2024-05-27 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 21, 29, 59, 20690, tzinfo=datetime.timezone.utc), verbose_name='Дата изменения(save)'),
        ),
    ]
