# Generated by Django 4.2.9 on 2024-05-27 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_taskmodel_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 22, 18, 48, 843473, tzinfo=datetime.timezone.utc), verbose_name='Дата изменения(save)'),
        ),
    ]
